name: Claude PR Review

on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened

jobs:
  claude_review:
    if: |
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.draft == false
      ) ||
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.user.type != 'Bot' &&
        contains(github.event.comment.body, '/claude-review')
      )
    uses: >-
      ActiveloopAI/shared-github-actions/.github/workflows/claude-pr-review.yaml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: "${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}"

  cleanup:
    needs: claude_review
    if: job.status != 'cancelled'
    runs-on: ubuntu-latest
    steps:
      - name: cleanup workflow runs
        uses: mattraks/delete-workflow-runs@v2.1.0
        with:
          token: "${{ github.token }}"
          repository: "${{ github.repository }}"
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: Claude PR Review
